apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: baseline-stack
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/TemplateMechanics/k8s-pilot.git
  ref:
    # Pin to a tag or commit for prod; branch is fine for dev/staging.
    branch: main
