apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baseline

commonLabels:
  app.kubernetes.io/name: baseline-web
  app.kubernetes.io/part-of: baseline-stack
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
