apiVersion: v1
kind: Service
metadata:
  name: baseline-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: baseline-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
